run:
	python manage.py runserver_plus

install:
	pip install -r requirements.txt

freeze:
	pip freeze > requirements.txt

migrate:
	python manage.py migrate

makemigrations:
	python manage.py makemigrations