# Generated by Django 4.0.4 on 2022-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationtechnology',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttechnology',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
