# Generated by Django 4.0.4 on 2022-07-31 10:45

from django.db import migrations
from django.utils.text import slugify

import autoslug.fields

DEFAULT = "abcd"


def forwards(apps, _):
    Technology = apps.get_model("technologies", "Technology")
    for obj in Technology.objects.all():
        obj.slug = slugify(obj.name)
        obj.save()


def backwards(apps, _):
    Technology = apps.get_model("technologies", "Technology")
    for obj in Technology.objects.all():
        obj.slug = DEFAULT
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("technologies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                default=DEFAULT,
                editable=True,
                populate_from="name",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, backwards),
    ]
