# Generated by Django 4.0.4 on 2022-04-30 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0001_initial'),
        ('collaborations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='collaborator',
            field=models.ForeignKey(limit_choices_to={'groups__name__in': ['developer', 'manager']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='technologies',
            field=models.ManyToManyField(through='technologies.CollaborationTechnology', to='technologies.technology'),
        ),
    ]
