# Generated by Django 4.0.4 on 2022-04-26 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='collaborator',
            field=models.ForeignKey(limit_choices_to={'is_developer': True, 'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
