# Generated by Django 4.0.4 on 2022-04-27 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborations', '0002_collaboration_ended_at_collaboration_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='collaborator',
            field=models.ForeignKey(limit_choices_to={'groups__name__in': ['developer', 'manager']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
