# Generated by Django 4.0.4 on 2022-04-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('projects', '0002_project_collaborations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='businesses.business'),
        ),
    ]
