# Generated by Django 4.0.4 on 2022-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', through='technologies.ProjectTechnology', to='technologies.technology'),
        ),
    ]
