# Generated by Django 4.0.4 on 2022-08-01 16:45

import autoslug.fields
from django.db import migrations
from django.utils.text import slugify

DEFAULT = "abcd"


def forwards(apps, _):
    Project = apps.get_model("projects", "Project")
    for obj in Project.objects.all():
        obj.slug = slugify(obj.name)
        obj.save()


def backwards(apps, _):
    Project = apps.get_model("projects", "Project")
    for obj in Project.objects.all():
        obj.slug = DEFAULT
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_technologies"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, default=DEFAULT, editable=True, populate_from="name"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, backwards),
    ]
