name: Checks
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'

      - name: Check Python version
        run: python --version

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Check Syntax
        run: flake8 .

      - name: Run Migrations
        run: python manage.py migrate
        
      - name: Run Test
        run: make test
