name: Heroku deploy staging

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'mycv-django-api-staging'
          heroku_email: 'diogo.gomes77@gmail.com'
